import Head from "next/head";
import Navbar from "../components/Navbar";
import Chat from "../components/Chat";
import { getChats, getUsers, unsubscribeSnapshots } from "../firebase";
export default function Home({ userChats, targetUsers, firstChat }) {
  return (
    <div>
      <Head>
        <title>Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid items-center ">
        <div className="flex h-screen overflow-hidden">
          <Navbar />
          <Chat
            userChats={userChats}
            targetUsers={targetUsers}
            firstChat={firstChat}
          />
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  unsubscribeSnapshots();
  const userID = context.req.cookies.userID;
  const userChats = await getChats(userID);
  const targetUsers = await getUsers(userChats, userID);

  return {
    props: { userChats, targetUsers, firstChat: userChats[0].id }, // will be passed to the page component as props
  };
}
