import Head from "next/head";
import { useRouter } from "next/router";

export default function Landing() {
  const router = useRouter();
  router.push("/home");
  return (
    <Head>
      <title>Messenger</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
